---
 - name: make ansible run a script
   hosts: localhost
   gather_facts: no

   tasks:
     - script: /home/student/mycode/python/pyhello2.py
       args:
         executable: python3 
         creates: /home/student/stopper.txt
       register: results
      
     - debug:
         var: results # debug var will always show the results to the screen.

